// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `TicketServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.purchasenear.service.ticket.interf;

public interface _TicketServiceOperations
{
    boolean createOrder(Order myOrder, Ice.Current __current);

    Order[] queryMyOrders(String phone, Ice.Current __current);

    boolean cancelOrder(long orderId, Ice.Current __current);
}
