// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GoodsService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.goods.rpcservice.ice.interf.goods;

public final class GoodsSearchServiceHelper
{
    public static void write(Ice.OutputStream __outS, GoodsSearchService __v)
    {
        __outS.writeObject(__v);
    }

    public static void read(Ice.InputStream __inS, GoodsSearchServiceHolder __h)
    {
        __inS.readObject(__h);
    }

    public static Ice.OptionalFormat optionalFormat()
    {
        return Ice.OptionalFormat.Class;
    }
}
