// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GoodsService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.goods.rpcservice.ice.interf.goods;

public final class GoodsSearchServicePrxHelper extends Ice.ObjectPrxHelperBase implements GoodsSearchServicePrx
{
    private static final String __search_name = "search";

    public SearchGoods search(SearchInfo info)
    {
        return search(info, null, false);
    }

    public SearchGoods search(SearchInfo info, java.util.Map<String, String> __ctx)
    {
        return search(info, __ctx, true);
    }

    private SearchGoods search(SearchInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "search", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("search");
                    __delBase = __getDelegate(false);
                    _GoodsSearchServiceDel __del = (_GoodsSearchServiceDel)__delBase;
                    return __del.search(info, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_search(SearchInfo info)
    {
        return begin_search(info, null, false, null);
    }

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx)
    {
        return begin_search(info, __ctx, true, null);
    }

    public Ice.AsyncResult begin_search(SearchInfo info, Ice.Callback __cb)
    {
        return begin_search(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_search(info, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_search(SearchInfo info, Callback_GoodsSearchService_search __cb)
    {
        return begin_search(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx, Callback_GoodsSearchService_search __cb)
    {
        return begin_search(info, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__search_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __search_name, __cb);
        try
        {
            __result.__prepare(__search_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            info.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public SearchGoods end_search(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __search_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            SearchGoods __ret;
            __ret = new SearchGoods();
            __ret.__read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static GoodsSearchServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GoodsSearchServicePrx)
            {
                __d = (GoodsSearchServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GoodsSearchServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GoodsSearchServicePrx)
            {
                __d = (GoodsSearchServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static GoodsSearchServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GoodsSearchServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static GoodsSearchServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof GoodsSearchServicePrx)
            {
                __d = (GoodsSearchServicePrx)__obj;
            }
            else
            {
                GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static GoodsSearchServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        GoodsSearchServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            GoodsSearchServicePrxHelper __h = new GoodsSearchServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::goods::GoodsSearchService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _GoodsSearchServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _GoodsSearchServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, GoodsSearchServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static GoodsSearchServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            GoodsSearchServicePrxHelper result = new GoodsSearchServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static void write(Ice.OutputStream __outS, GoodsSearchServicePrx v)
    {
        __outS.writeProxy(v);
    }

    public static GoodsSearchServicePrx read(Ice.InputStream __inS)
    {
        Ice.ObjectPrx proxy = __inS.readProxy();
        if(proxy != null)
        {
            GoodsSearchServicePrxHelper result = new GoodsSearchServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static Ice.OptionalFormat optionalFormat()
    {
        return Ice.OptionalFormat.FSize;
    }

    public static final long serialVersionUID = 0L;
}
