// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GoodsService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.goods.rpcservice.ice.interf.goods;

public final class goodsInfoListHelper
{
    public static void
    write(IceInternal.BasicStream __os, GoodsInfo[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                __v[__i0].__write(__os);
            }
        }
    }

    public static GoodsInfo[]
    read(IceInternal.BasicStream __is)
    {
        GoodsInfo[] __v;
        final int __len0 = __is.readAndCheckSeqSize(75);
        __v = new GoodsInfo[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = new GoodsInfo();
            __v[__i0].__read(__is);
        }
        return __v;
    }

    public static void write(Ice.OutputStream __outS, GoodsInfo[] __v)
    {
        if(__v == null)
        {
            __outS.writeSize(0);
        }
        else
        {
            __outS.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                __v[__i0].ice_write(__outS);
            }
        }
    }

    public static GoodsInfo[] read(Ice.InputStream __inS)
    {
        GoodsInfo[] __v;
        final int __len0 = __inS.readAndCheckSeqSize(75);
        __v = new GoodsInfo[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = new GoodsInfo();
            __v[__i0].ice_read(__inS);
        }
        return __v;
    }

    public static Ice.OptionalFormat optionalFormat()
    {
        return Ice.OptionalFormat.FSize;
    }
}
