// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GoodsService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.goods.rpcservice.ice.interf.goods;

public interface GoodsSearchServicePrx extends Ice.ObjectPrx
{
    public SearchGoods search(SearchInfo info);

    public SearchGoods search(SearchInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_search(SearchInfo info);

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_search(SearchInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_search(SearchInfo info, Callback_GoodsSearchService_search __cb);

    public Ice.AsyncResult begin_search(SearchInfo info, java.util.Map<String, String> __ctx, Callback_GoodsSearchService_search __cb);

    public SearchGoods end_search(Ice.AsyncResult __result);
}
