// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GoodsService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.goods.rpcservice.ice.interf.goods;

public final class SearchGoodsHelper
{
    public static void write(Ice.OutputStream __outS, SearchGoods __v)
    {
        __v.ice_write(__outS);
    }

    public static SearchGoods read(Ice.InputStream __inS)
    {
        SearchGoods __v = new SearchGoods();
        __v.ice_read(__inS);
        return __v;
    }

    public static Ice.OptionalFormat optionalFormat()
    {
        return Ice.OptionalFormat.FSize;
    }
}
