// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `Logout.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.logout;

public interface UserService extends Ice.Object,
                                     _UserServiceOperations, _UserServiceOperationsNC
{
    public static final String ice_staticId = "::logout::UserService";

    public static final long serialVersionUID = 895308923L;
}
