// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `Logout.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.logout;

public interface UserServicePrx extends Ice.ObjectPrx
{
    public int logout(long userid, String token);

    public int logout(long userid, String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(long userid, String token);

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(long userid, String token, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(long userid, String token, Callback_UserService_logout __cb);

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx, Callback_UserService_logout __cb);

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public int end_logout(Ice.AsyncResult __result);
}
