// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `Logout.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.logout;

public final class UserServicePrxHelper extends Ice.ObjectPrxHelperBase implements UserServicePrx
{
    private static final String __logout_name = "logout";

    public int logout(long userid, String token)
    {
        return logout(userid, token, null, false);
    }

    public int logout(long userid, String token, java.util.Map<String, String> __ctx)
    {
        return logout(userid, token, __ctx, true);
    }

    private int logout(long userid, String token, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__logout_name);
        return end_logout(begin_logout(userid, token, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_logout(long userid, String token)
    {
        return begin_logout(userid, token, null, false, false, null);
    }

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx)
    {
        return begin_logout(userid, token, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_logout(long userid, String token, Ice.Callback __cb)
    {
        return begin_logout(userid, token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_logout(userid, token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_logout(long userid, String token, Callback_UserService_logout __cb)
    {
        return begin_logout(userid, token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_logout(long userid, String token, java.util.Map<String, String> __ctx, Callback_UserService_logout __cb)
    {
        return begin_logout(userid, token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_logout(userid, token, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_logout(userid, token, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_logout(userid, token, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_logout(long userid, 
                                        String token, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_IntCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_logout(userid, token, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_logout(long userid, 
                                         String token, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_logout(userid, token, __ctx, __explicitCtx, __synchronous, 
                            new IceInternal.Functional_TwowayCallbackInt(__responseCb, __exceptionCb, __sentCb)
                                {
                                    public final void __completed(Ice.AsyncResult __result)
                                    {
                                        UserServicePrxHelper.__logout_completed(this, __result);
                                    }
                                });
    }

    private Ice.AsyncResult begin_logout(long userid, 
                                         String token, 
                                         java.util.Map<String, String> __ctx, 
                                         boolean __explicitCtx, 
                                         boolean __synchronous, 
                                         IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__logout_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__logout_name, __cb);
        try
        {
            __result.prepare(__logout_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeLong(userid);
            __os.writeString(token);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public int end_logout(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __logout_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __logout_completed(Ice.TwowayCallbackInt __cb, Ice.AsyncResult __result)
    {
        cn.purchasenear.v1.user.logout.UserServicePrx __proxy = (cn.purchasenear.v1.user.logout.UserServicePrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_logout(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static UserServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static UserServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, UserServicePrx.class, UserServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::logout::UserService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, UserServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static UserServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            UserServicePrxHelper result = new UserServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
