// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ResetService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.service.reset.Reset;

public class ResetInfo implements java.lang.Cloneable, java.io.Serializable
{
    public long orderId;

    public long flashSalesId;

    public ResetInfo()
    {
    }

    public ResetInfo(long orderId, long flashSalesId)
    {
        this.orderId = orderId;
        this.flashSalesId = flashSalesId;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ResetInfo _r = null;
        if(rhs instanceof ResetInfo)
        {
            _r = (ResetInfo)rhs;
        }

        if(_r != null)
        {
            if(orderId != _r.orderId)
            {
                return false;
            }
            if(flashSalesId != _r.flashSalesId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::Reset::ResetInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, orderId);
        __h = IceInternal.HashUtil.hashAdd(__h, flashSalesId);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(orderId);
        __os.writeLong(flashSalesId);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        orderId = __is.readLong();
        flashSalesId = __is.readLong();
    }

    public static final long serialVersionUID = -2002193709L;
}
