// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ResetService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.service.reset.Reset;

public interface ResetServicePrx extends Ice.ObjectPrx
{
    public ResetInfo flashsales(long orderId, long flashSalesId);

    public ResetInfo flashsales(long orderId, long flashSalesId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId, Ice.Callback __cb);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId, Callback_ResetService_flashsales __cb);

    public Ice.AsyncResult begin_flashsales(long orderId, long flashSalesId, java.util.Map<String, String> __ctx, Callback_ResetService_flashsales __cb);

    public ResetInfo end_flashsales(Ice.AsyncResult __result);
}
