// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `TicketServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.purchasenear.service.ticket.interf;

public final class TicketServicePrxHelper extends Ice.ObjectPrxHelperBase implements TicketServicePrx
{
    private static final String __cancelOrder_name = "cancelOrder";

    public boolean cancelOrder(long orderId)
    {
        return cancelOrder(orderId, null, false);
    }

    public boolean cancelOrder(long orderId, java.util.Map<String, String> __ctx)
    {
        return cancelOrder(orderId, __ctx, true);
    }

    private boolean cancelOrder(long orderId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "cancelOrder", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("cancelOrder");
                    __delBase = __getDelegate(false);
                    _TicketServiceDel __del = (_TicketServiceDel)__delBase;
                    return __del.cancelOrder(orderId, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId)
    {
        return begin_cancelOrder(orderId, null, false, null);
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId, java.util.Map<String, String> __ctx)
    {
        return begin_cancelOrder(orderId, __ctx, true, null);
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId, Ice.Callback __cb)
    {
        return begin_cancelOrder(orderId, null, false, __cb);
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_cancelOrder(orderId, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId, Callback_TicketService_cancelOrder __cb)
    {
        return begin_cancelOrder(orderId, null, false, __cb);
    }

    public Ice.AsyncResult begin_cancelOrder(long orderId, java.util.Map<String, String> __ctx, Callback_TicketService_cancelOrder __cb)
    {
        return begin_cancelOrder(orderId, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_cancelOrder(long orderId, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__cancelOrder_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __cancelOrder_name, __cb);
        try
        {
            __result.__prepare(__cancelOrder_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeLong(orderId);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public boolean end_cancelOrder(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __cancelOrder_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __createOrder_name = "createOrder";

    public boolean createOrder(Order myOrder)
    {
        return createOrder(myOrder, null, false);
    }

    public boolean createOrder(Order myOrder, java.util.Map<String, String> __ctx)
    {
        return createOrder(myOrder, __ctx, true);
    }

    private boolean createOrder(Order myOrder, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "createOrder", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("createOrder");
                    __delBase = __getDelegate(false);
                    _TicketServiceDel __del = (_TicketServiceDel)__delBase;
                    return __del.createOrder(myOrder, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder)
    {
        return begin_createOrder(myOrder, null, false, null);
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder, java.util.Map<String, String> __ctx)
    {
        return begin_createOrder(myOrder, __ctx, true, null);
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder, Ice.Callback __cb)
    {
        return begin_createOrder(myOrder, null, false, __cb);
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_createOrder(myOrder, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder, Callback_TicketService_createOrder __cb)
    {
        return begin_createOrder(myOrder, null, false, __cb);
    }

    public Ice.AsyncResult begin_createOrder(Order myOrder, java.util.Map<String, String> __ctx, Callback_TicketService_createOrder __cb)
    {
        return begin_createOrder(myOrder, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_createOrder(Order myOrder, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__createOrder_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __createOrder_name, __cb);
        try
        {
            __result.__prepare(__createOrder_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            myOrder.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public boolean end_createOrder(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __createOrder_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    private static final String __queryMyOrders_name = "queryMyOrders";

    public Order[] queryMyOrders(String phone)
    {
        return queryMyOrders(phone, null, false);
    }

    public Order[] queryMyOrders(String phone, java.util.Map<String, String> __ctx)
    {
        return queryMyOrders(phone, __ctx, true);
    }

    private Order[] queryMyOrders(String phone, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "queryMyOrders", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("queryMyOrders");
                    __delBase = __getDelegate(false);
                    _TicketServiceDel __del = (_TicketServiceDel)__delBase;
                    return __del.queryMyOrders(phone, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone)
    {
        return begin_queryMyOrders(phone, null, false, null);
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone, java.util.Map<String, String> __ctx)
    {
        return begin_queryMyOrders(phone, __ctx, true, null);
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone, Ice.Callback __cb)
    {
        return begin_queryMyOrders(phone, null, false, __cb);
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_queryMyOrders(phone, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone, Callback_TicketService_queryMyOrders __cb)
    {
        return begin_queryMyOrders(phone, null, false, __cb);
    }

    public Ice.AsyncResult begin_queryMyOrders(String phone, java.util.Map<String, String> __ctx, Callback_TicketService_queryMyOrders __cb)
    {
        return begin_queryMyOrders(phone, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_queryMyOrders(String phone, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__queryMyOrders_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __queryMyOrders_name, __cb);
        try
        {
            __result.__prepare(__queryMyOrders_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(phone);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public Order[] end_queryMyOrders(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __queryMyOrders_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            Order[] __ret;
            __ret = OrderSeqHelper.read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static TicketServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof TicketServicePrx)
            {
                __d = (TicketServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    TicketServicePrxHelper __h = new TicketServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static TicketServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof TicketServicePrx)
            {
                __d = (TicketServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    TicketServicePrxHelper __h = new TicketServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static TicketServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    TicketServicePrxHelper __h = new TicketServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static TicketServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    TicketServicePrxHelper __h = new TicketServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static TicketServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof TicketServicePrx)
            {
                __d = (TicketServicePrx)__obj;
            }
            else
            {
                TicketServicePrxHelper __h = new TicketServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static TicketServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        TicketServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            TicketServicePrxHelper __h = new TicketServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::interf::TicketService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _TicketServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _TicketServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, TicketServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static TicketServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            TicketServicePrxHelper result = new TicketServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static void write(Ice.OutputStream __outS, TicketServicePrx v)
    {
        __outS.writeProxy(v);
    }

    public static TicketServicePrx read(Ice.InputStream __inS)
    {
        Ice.ObjectPrx proxy = __inS.readProxy();
        if(proxy != null)
        {
            TicketServicePrxHelper result = new TicketServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static Ice.OptionalFormat optionalFormat()
    {
        return Ice.OptionalFormat.FSize;
    }

    public static final long serialVersionUID = 0L;
}
