// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.regist;

public abstract class Callback_UserService_regist extends Ice.TwowayCallback
{
    public abstract void response(ActivateInfo __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        UserServicePrx __proxy = (UserServicePrx)__result.getProxy();
        ActivateInfo __ret = null;
        try
        {
            __ret = __proxy.end_regist(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
