// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.regist;

public interface UserServicePrx extends Ice.ObjectPrx
{
    public ActivateInfo regist(ClientInfo info);

    public ActivateInfo regist(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_regist(ClientInfo info);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_regist(ClientInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, Callback_UserService_regist __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Callback_UserService_regist __cb);

    public ActivateInfo end_regist(Ice.AsyncResult __result);
}
