// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.user.regist;

public final class UserServicePrxHelper extends Ice.ObjectPrxHelperBase implements UserServicePrx
{
    private static final String __regist_name = "regist";

    public ActivateInfo regist(ClientInfo info)
    {
        return regist(info, null, false);
    }

    public ActivateInfo regist(ClientInfo info, java.util.Map<String, String> __ctx)
    {
        return regist(info, __ctx, true);
    }

    private ActivateInfo regist(ClientInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "regist", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("regist");
                    __delBase = __getDelegate(false);
                    _UserServiceDel __del = (_UserServiceDel)__delBase;
                    return __del.regist(info, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_regist(ClientInfo info)
    {
        return begin_regist(info, null, false, null);
    }

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx)
    {
        return begin_regist(info, __ctx, true, null);
    }

    public Ice.AsyncResult begin_regist(ClientInfo info, Ice.Callback __cb)
    {
        return begin_regist(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_regist(info, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_regist(ClientInfo info, Callback_UserService_regist __cb)
    {
        return begin_regist(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Callback_UserService_regist __cb)
    {
        return begin_regist(info, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__regist_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __regist_name, __cb);
        try
        {
            __result.__prepare(__regist_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            info.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public ActivateInfo end_regist(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __regist_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            ActivateInfo __ret;
            __ret = new ActivateInfo();
            __ret.__read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof UserServicePrx)
            {
                __d = (UserServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    UserServicePrxHelper __h = new UserServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof UserServicePrx)
            {
                __d = (UserServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    UserServicePrxHelper __h = new UserServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    UserServicePrxHelper __h = new UserServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static UserServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    UserServicePrxHelper __h = new UserServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static UserServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof UserServicePrx)
            {
                __d = (UserServicePrx)__obj;
            }
            else
            {
                UserServicePrxHelper __h = new UserServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static UserServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        UserServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            UserServicePrxHelper __h = new UserServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::regist::UserService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _UserServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _UserServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, UserServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static UserServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            UserServicePrxHelper result = new UserServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
