// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `CartService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.cart.ice.interf;

public interface CartServicePrx extends Ice.ObjectPrx
{
    public OpCartInfo addCart(CartInfo info);

    public OpCartInfo addCart(CartInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addCart(CartInfo info);

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addCart(CartInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addCart(CartInfo info, Callback_CartService_addCart __cb);

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx, Callback_CartService_addCart __cb);

    public OpCartInfo end_addCart(Ice.AsyncResult __result);
}
