// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `CartService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.purchasenear.v1.cart.ice.interf;

public final class CartServicePrxHelper extends Ice.ObjectPrxHelperBase implements CartServicePrx
{
    private static final String __addCart_name = "addCart";

    public OpCartInfo addCart(CartInfo info)
    {
        return addCart(info, null, false);
    }

    public OpCartInfo addCart(CartInfo info, java.util.Map<String, String> __ctx)
    {
        return addCart(info, __ctx, true);
    }

    private OpCartInfo addCart(CartInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "addCart", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("addCart");
                    __delBase = __getDelegate(false);
                    _CartServiceDel __del = (_CartServiceDel)__delBase;
                    return __del.addCart(info, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_addCart(CartInfo info)
    {
        return begin_addCart(info, null, false, null);
    }

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx)
    {
        return begin_addCart(info, __ctx, true, null);
    }

    public Ice.AsyncResult begin_addCart(CartInfo info, Ice.Callback __cb)
    {
        return begin_addCart(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_addCart(info, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_addCart(CartInfo info, Callback_CartService_addCart __cb)
    {
        return begin_addCart(info, null, false, __cb);
    }

    public Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx, Callback_CartService_addCart __cb)
    {
        return begin_addCart(info, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_addCart(CartInfo info, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__addCart_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __addCart_name, __cb);
        try
        {
            __result.__prepare(__addCart_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            info.__write(__os);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public OpCartInfo end_addCart(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __addCart_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            OpCartInfo __ret;
            __ret = new OpCartInfo();
            __ret.__read(__is);
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static CartServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CartServicePrx)
            {
                __d = (CartServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    CartServicePrxHelper __h = new CartServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static CartServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CartServicePrx)
            {
                __d = (CartServicePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    CartServicePrxHelper __h = new CartServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static CartServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    CartServicePrxHelper __h = new CartServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static CartServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    CartServicePrxHelper __h = new CartServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static CartServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof CartServicePrx)
            {
                __d = (CartServicePrx)__obj;
            }
            else
            {
                CartServicePrxHelper __h = new CartServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static CartServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        CartServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            CartServicePrxHelper __h = new CartServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::cart::CartService"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _CartServiceDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _CartServiceDelD();
    }

    public static void __write(IceInternal.BasicStream __os, CartServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static CartServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            CartServicePrxHelper result = new CartServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
